codecov:
  max_report_age: off
  notify:
    after_n_builds: 4

coverage:
  status:
    project:
      default:
        threshold: 1
    patch:
      default:
        target: 0%
        threshold: 1

github_checks:
  annotations: false
