package org.cru.godtools.base.ui.theme

import androidx.compose.ui.graphics.Color

// The following colors were automatically generated using the material 3 theme builder:
// https://m3.material.io/theme-builder#/custom
// Primary: #3BA4DB
// Secondary: #3BA4DB
// Neutral: #8F9193
// Color match: false
// Extended Colors:
//   Green: #6EDC50
//   Red: #E55B36

internal val primaryLight = Color(0xFF216487)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFC7E7FF)
internal val onPrimaryContainerLight = Color(0xFF004C6C)
internal val secondaryLight = Color(0xFF216487)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFC7E7FF)
internal val onSecondaryContainerLight = Color(0xFF004C6C)
internal val tertiaryLight = Color(0xFF62597C)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFE8DDFF)
internal val onTertiaryContainerLight = Color(0xFF4A4263)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF6FAFE)
internal val onBackgroundLight = Color(0xFF181C20)
internal val surfaceLight = Color(0xFFF6FAFE)
internal val onSurfaceLight = Color(0xFF171C1F)
internal val surfaceVariantLight = Color(0xFFDDE3EA)
internal val onSurfaceVariantLight = Color(0xFF41484D)
internal val outlineLight = Color(0xFF71787E)
internal val outlineVariantLight = Color(0xFFC1C7CE)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2C3134)
internal val inverseOnSurfaceLight = Color(0xFFEDF1F5)
internal val inversePrimaryLight = Color(0xFF92CEF5)
internal val surfaceDimLight = Color(0xFFD6DBDE)
internal val surfaceBrightLight = Color(0xFFF6FAFE)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF0F4F8)
internal val surfaceContainerLight = Color(0xFFEAEEF2)
internal val surfaceContainerHighLight = Color(0xFFE4E9EC)
internal val surfaceContainerHighestLight = Color(0xFFDFE3E7)

internal val primaryDark = Color(0xFF92CEF5)
internal val onPrimaryDark = Color(0xFF00344C)
internal val primaryContainerDark = Color(0xFF004C6C)
internal val onPrimaryContainerDark = Color(0xFFC7E7FF)
internal val secondaryDark = Color(0xFF92CEF5)
internal val onSecondaryDark = Color(0xFF00344C)
internal val secondaryContainerDark = Color(0xFF004C6C)
internal val onSecondaryContainerDark = Color(0xFFC7E7FF)
internal val tertiaryDark = Color(0xFFCCC1E9)
internal val onTertiaryDark = Color(0xFF342B4B)
internal val tertiaryContainerDark = Color(0xFF4A4263)
internal val onTertiaryContainerDark = Color(0xFFE8DDFF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF101417)
internal val onBackgroundDark = Color(0xFFDFE3E7)
internal val surfaceDark = Color(0xFF0F1417)
internal val onSurfaceDark = Color(0xFFDFE3E7)
internal val surfaceVariantDark = Color(0xFF41484D)
internal val onSurfaceVariantDark = Color(0xFFC1C7CE)
internal val outlineDark = Color(0xFF8B9198)
internal val outlineVariantDark = Color(0xFF41484D)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDFE3E7)
internal val inverseOnSurfaceDark = Color(0xFF2C3134)
internal val inversePrimaryDark = Color(0xFF216487)
internal val surfaceDimDark = Color(0xFF0F1417)
internal val surfaceBrightDark = Color(0xFF353A3D)
internal val surfaceContainerLowestDark = Color(0xFF0A0F12)
internal val surfaceContainerLowDark = Color(0xFF171C1F)
internal val surfaceContainerDark = Color(0xFF1B2023)
internal val surfaceContainerHighDark = Color(0xFF262B2E)
internal val surfaceContainerHighestDark = Color(0xFF303538)

internal val greenLight = Color(0xFF416834)
internal val onGreenLight = Color(0xFFFFFFFF)
internal val greenContainerLight = Color(0xFFC2EFAE)
internal val onGreenContainerLight = Color(0xFF2A4F1F)
internal val redLight = Color(0xFF8F4B39)
internal val onRedLight = Color(0xFFFFFFFF)
internal val redContainerLight = Color(0xFFFFDBD1)
internal val onRedContainerLight = Color(0xFF723524)

internal val greenDark = Color(0xFFA7D394)
internal val onGreenDark = Color(0xFF13380A)
internal val greenContainerDark = Color(0xFF2A4F1F)
internal val onGreenContainerDark = Color(0xFFC2EFAE)
internal val redDark = Color(0xFFFFB4A1)
internal val onRedDark = Color(0xFF561F10)
internal val redContainerDark = Color(0xFF723524)
internal val onRedContainerDark = Color(0xFFFFDBD1)
