name: Crowdin Translation Download

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: Download Latest Strings from Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Strings from Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: false
          download_translations: true
          skip_untranslated_strings: true
          localization_branch_name: "chore/crowdinTranslations"
          pull_request_title: "Update Translations"
          commit_message: "Download the latest translations from Crowdin"
        env:
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
