name: "Validate Gradle Wrapper"

on:
  push:
    branches: [develop, master, feature/*]
  pull_request:
    branches: [develop, master, feature/*]

jobs:
  validate-gradle-wrapper:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
